export const myTheme = {
  name: 'my-theme',
  settings: [
    {
      scope: ['comment', 'markup.quote.markdown', 'meta.diff', 'meta.diff.header'],
      settings: {
        foreground: '#b3b3b3',
      },
    },
    {
      scope: [
        'meta.template.expression.js',
        'constant.name.attribute.tag.jade',
        'punctuation.definition.metadata.markdown',
        'punctuation.definition.string.end.markdown',
        'punctuation.definition.string.begin.markdown',
      ],
      settings: {
        foreground: '#ffffff',
      },
    },
    {
      scope: [
        'variable',
        'support.variable',
        'entity.name.tag.yaml',
        'constant.character.entity.html',
        'source.css entity.name.tag.reference',
        'beginning.punctuation.definition.list.markdown',
        'source.css entity.other.attribute-name.parent-selector',
        'meta.structure.dictionary.json support.type.property-name',
      ],
      settings: {
        foreground: '#47d18c',
      },
    },
    {
      scope: [
        'markup.bold',
        'constant.numeric',
        'meta.group.regexp',
        'constant.other.php',
        'support.constant.ext.php',
        'constant.other.class.php',
        'support.constant.core.php',
        'fenced_code.block.language',
        'constant.other.caps.python',
        'entity.other.attribute-name',
        'support.type.exception.python',
        'source.css keyword.other.unit',
        'variable.other.object.property.js.jsx',
        'variable.other.object.js',
      ],
      settings: {
        foreground: '#ff990a',
      },
    },
    {
      scope: [
        'markup.list',
        'text.xml string',
        'entity.name.type',
        'support.function',
        'entity.other.attribute-name',
        'meta.at-rule.extend',
        'entity.name.function',
        'entity.other.inherited-class',
        'entity.other.keyframe-offset.css',
        'text.html.markdown string.quoted',
        'meta.function-call.generic.python',
        'meta.at-rule.extend support.constant',
        'entity.other.attribute-name.class.jade',
        'source.css entity.other.attribute-name',
        'text.xml punctuation.definition.string',
      ],
      settings: {
        foreground: '#47d18c',
      },
    },
    {
      scope: ['markup.heading', 'variable.language.this.js', 'variable.language.special.self.python'],
      settings: {
        foreground: '#66a3ff',
      },
    },
    {
      scope: [
        'punctuation.definition.interpolation',
        'punctuation.section.embedded.end.php',
        'punctuation.section.embedded.end.ruby',
        'punctuation.section.embedded.begin.php',
        'punctuation.section.embedded.begin.ruby',
        'punctuation.definition.template-expression',
        'entity.name.tag',
      ],
      settings: {
        foreground: '#f6558c',
      },
    },
    {
      scope: ['storage', 'keyword', 'meta.link', 'meta.image', 'markup.italic', 'source.js support.type'],
      settings: {
        foreground: '#66a3ff',
      },
    },
    {
      scope: ['string.regexp', 'markup.changed'],
      settings: {
        foreground: '#7cb7ff',
      },
    },
    {
      scope: [
        'constant',
        'support.class',
        'keyword.operator',
        'support.constant',
        'text.html.markdown string',
        'source.css support.function',
        'source.php support.function',
        'support.function.magic.python',
        'entity.other.attribute-name.id',
        'markup.deleted',
      ],
      settings: {
        foreground: '#f6558c',
      },
    },
    {
      scope: [
        'string',
        'text.html.php string',
        'markup.inline.raw',
        'markup.inserted',
        'punctuation.definition.string',
        'punctuation.definition.markdown',
        'text.html meta.embedded source.js string',
        'text.html.php punctuation.definition.string',
        'text.html meta.embedded source.js punctuation.definition.string',
        'text.html punctuation.definition.string',
        'text.html string',
      ],
      settings: {
        foreground: '#47d18c',
      },
    },
    {
      scope: ['entity.other.inherited-class'],
      settings: {
        fontStyle: 'underline',
      },
    },
    {
      scope: ['punctuation', 'embed'],
      settings: {
        foreground: '#ffffff',
      },
    },
  ],
  colors: {
    'activityBar.background': 'transparent',
    'activityBar.dropBackground': 'transparent',
    'activityBar.foreground': '#ffffff',
    'activityBarBadge.background': '#078345',
    'activityBarBadge.foreground': '#18191b',
    'badge.background': '#078345',
    'badge.foreground': '#18191b',
    'button.background': '#47d18c',
    'button.hoverBackground': '#078345',
    'debugExceptionWidget.background': '#a86624',
    'debugExceptionWidget.border': '#a86624',
    'debugToolBar.background': 'transparent',
    'diffEditor.insertedTextBackground': '#47d18c20', // Green for inserted text
    'diffEditor.removedTextBackground': '#f6558c20', // Red for removed text
    'diffEditor.insertedTextForeground': '#47d18c', // Green for inserted text foreground
    'diffEditor.removedTextForeground': '#b3b3b3', // Gray for removed text foreground
    'dropdown.background': 'transparent',
    'dropdown.border': 'transparent',
    'editor.background': 'transparent',
    'editor.findMatchBackground': '#ff990a56',
    'editor.findMatchBorder': '#ff990ab6',
    'editor.findMatchHighlightBackground': '#66a3ff77',
    'editor.foreground': '#ffffff',
    'editor.hoverHighlightBackground': '#a35200',
    'editor.lineHighlightBackground': '#a86624',
    'editor.lineHighlightBorder': '#a86624',
    'editor.rangeHighlightBackground': '#206cdf',
    'editor.selectionBackground': '#47d18c',
    'editor.selectionHighlightBackground': '#47d18c80',
    'editor.wordHighlightBackground': '#f6558c',
    'editor.wordHighlightStrongBackground': '#a8662480',
    'editorBracketMatch.background': '#18191b',
    'editorBracketMatch.border': '#18191b',
    'editorCodeLens.foreground': '#206cdf',
    'editorCursor.foreground': '#ffffff',
    'editorError.foreground': '#f6558c',
    'editorGroup.background': 'transparent',
    'editorGroup.dropBackground': '#a86624d7',
    'editorGroupHeader.tabsBackground': 'transparent',
    'editorGutter.addedBackground': '#078345bb',
    'editorGutter.deletedBackground': '#f6558cbb',
    'editorGutter.modifiedBackground': '#206cdfbb',
    'editorHoverWidget.background': '#a35200',
    'editorHoverWidget.border': '#078345',
    'editorIndentGuide.activeBackground': '#ff990a',
    'editorIndentGuide.background': '#18191b',
    'editorLineNumber.foreground': '#206cdf',
    'editorLink.activeForeground': '#206cdf',
    'editorOverviewRuler.border': '#18191b',
    'editorRuler.foreground': '#206cdf',
    'editorSuggestWidget.background': '#18191b',
    'editorSuggestWidget.border': '#078345',
    'editorSuggestWidget.selectedBackground': '#a35200',
    'editorWarning.foreground': '#ff990a',
    'editorWhitespace.foreground': '#18191b',
    'editorWidget.background': 'transparent',
    errorForeground: '#f6558c',
    'extensionButton.prominentBackground': '#078345',
    'extensionButton.prominentHoverBackground': '#078345b0',
    focusBorder: '#206cdf',
    foreground: '#ffffff',
    'gitDecoration.ignoredResourceForeground': '#555555',
    'input.background': 'transparent',
    'input.placeholderForeground': '#206cdf',
    'inputOption.activeBorder': '#f6558c',
    'inputValidation.errorBackground': '#f6558c',
    'inputValidation.errorBorder': '#f6558c',
    'inputValidation.infoBackground': '#206cdf',
    'inputValidation.infoBorder': '#206cdf',
    'inputValidation.warningBackground': '#ff990a',
    'inputValidation.warningBorder': '#ff990a',
    'list.activeSelectionBackground': 'transparent',
    'list.activeSelectionForeground': '#47d18c',
    'list.dropBackground': '#a86624',
    'list.focusBackground': '#18191b',
    'list.focusForeground': '#ffffff',
    'list.hoverBackground': 'transparent',
    'list.hoverForeground': '#ffffff',
    'list.inactiveSelectionBackground': 'transparent',
    'list.inactiveSelectionForeground': '#47d18c',
    'merge.currentContentBackground': '#f6558c40',
    'merge.currentHeaderBackground': '#f6558c80',
    'merge.incomingContentBackground': '#206cdf40',
    'merge.incomingHeaderBackground': '#206cdf80',
    'notification.background': 'transparent',
    'notification.foreground': '#ffffff',
    'notification.infoBackground': 'transparent',
    'notification.infoForeground': '#ffffff',
    'panel.background': 'transparent',
    'panel.border': '#18191b',
    'panelTitle.activeBorder': '#206cdf',
    'panelTitle.activeForeground': '#47d18c',
    'panelTitle.inactiveForeground': '#ffffff',
    'pickerGroup.border': '#ffffff',
    'pickerGroup.foreground': '#ffffff',
    'progressBar.background': '#206cdf',
    'quickInput.background': 'transparent',
    'scrollbar.shadow': 'transparent',
    'scrollbarSlider.activeBackground': '#206cdf',
    'scrollbarSlider.background': '#206cdf',
    'scrollbarSlider.hoverBackground': '#206cdf',
    'selection.background': '#f6558c',
    'settings.headerForeground': '#f6558c',
    'sideBar.background': 'transparent',
    'sideBar.border': '#18191b',
    'sideBar.foreground': '#ffffff',
    'sideBarSectionHeader.background': 'transparent',
    'sideBarSectionHeader.border': '#18191b',
    'sideBarTitle.foreground': '#ffffff',
    'statusBar.background': 'transparent',
    'statusBar.foreground': '#ffffff',
    'statusBar.noFolderBackground': 'transparent',
    'statusBarItem.hoverBackground': '#47d18c',
    'statusBarItem.prominentBackground': '#47d18c',
    'statusBarItem.prominentHoverBackground': '#47d18cb3',
    'statusBarItem.remoteBackground': '#47d18c',
    'statusBarItem.remoteForeground': '#18191b',
    'tab.activeBackground': 'transparent',
    'tab.activeBorder': '#47d18c',
    'tab.activeForeground': '#ffffff',
    'tab.border': '#18191b',
    'tab.hoverBackground': '#47d18c',
    'tab.hoverBorder': '#47d18c',
    'tab.inactiveBackground': 'transparent',
    'tab.inactiveForeground': '#ffffff',
    'tab.unfocusedHoverBackground': '#47d18c',
    'terminal.ansiBlack': '#18191b',
    'terminal.ansiBlue': '#206cdf',
    'terminal.ansiBrightBlack': '#555555',
    'terminal.ansiBrightBlue': '#206cdf',
    'terminal.ansiBrightCyan': '#47d18c',
    'terminal.ansiBrightGreen': '#47d18c',
    'terminal.ansiBrightMagenta': '#f6558c',
    'terminal.ansiBrightRed': '#f6558c',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBrightYellow': '#ff990a',
    'terminal.ansiCyan': '#47d18c',
    'terminal.ansiGreen': '#47d18c',
    'terminal.ansiMagenta': '#f6558c',
    'terminal.ansiRed': '#f6558c',
    'terminal.ansiWhite': '#ffffff',
    'terminal.ansiYellow': '#ff990a',
    'textBlockQuote.background': '#a86624',
    'textBlockQuote.border': '#a86624',
    'textCodeBlock.background': '#a86624',
    'textLink.activeForeground': '#206cdf',
    'textLink.foreground': '#206cdf',
    'textPreformat.foreground': '#206cdf',
    'titleBar.activeBackground': 'transparent',
    'titleBar.activeForeground': '#ffffff',
    'titleBar.inactiveBackground': 'transparent',
    'titleBar.inactiveForeground': '#ffffff',
    'tree.indentGuidesStroke': '#18191b',
    'widget.shadow': 'transparent',
  },
  type: 'dark',
};
